import { repairArabicObject } from './repairArabicText.js';

const dashboardSharedCopy = {
  en: {
    backToSite: 'Back to site',
    appearance: 'Appearance',
    language: 'Language',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    logout: 'Logout',
    loggingOut: 'Logging out...',
    phoneLabel: 'Mobile number',
    phoneHelp: 'Used for WhatsApp appointment updates. Email notifications will still continue.',
    phoneInvalid: 'Enter a valid 8-digit Kuwaiti phone number.',
    phonePlaceholder: '4XXXXXXX',
    choosePhoto: 'Choose from device',
    takePhoto: 'Take photo',
    removePhoto: 'Remove photo',
    saveChanges: 'Save changes',
    profileNameLabel: 'Display name',
    profilePhoneLabel: 'Mobile number',
    profilePhoneHelp: 'Used for booking notifications and account contact.',
    profilePhoneInvalid: 'Enter a valid 8-digit Kuwaiti phone number.',
    profileSettings: 'Profile settings',
    profileSettingsBody: 'Update your name and mobile number directly from the admin shell.',
    profilePhotoLabel: 'Profile photo',
    profilePhotoBody: 'Upload a clear square profile image for the sidebar and admin shell.',
    changePhoto: 'Change photo',
    preparing: 'Preparing...',
    themeSettings: 'Theme',
    themeLight: 'Light mode',
    themeDark: 'Dark mode',
    languageSettings: 'Language',
    languageEnglish: 'English',
    languageArabic: 'Arabic',
    settingsWorkspaceTitle: 'Workspace preferences',
    settingsWorkspaceBody:
      'Control the admin shell, update your profile presence, and keep your operating environment comfortable for long days.',
  },
  ar: {
    backToSite: 'العودة إلى الموقع',
    appearance: 'المظهر',
    language: 'اللغة',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    logout: 'تسجيل الخروج',
    loggingOut: 'جار تسجيل الخروج...',
    phoneLabel: 'رقم الجوال',
    phoneHelp: 'يُستخدم لإشعارات المواعيد عبر WhatsApp. وستستمر إشعارات البريد الإلكتروني أيضاً.',
    phoneInvalid: 'أدخل رقم جوال كويتي صحيح مكوّن من 8 أرقام.',
    phonePlaceholder: '4XXXXXXX',
    choosePhoto: 'اختر من الجهاز',
    takePhoto: 'التقاط صورة',
    removePhoto: 'إزالة الصورة',
    saveChanges: 'حفظ التغييرات',
    profileNameLabel: 'اسم العرض',
    profilePhoneLabel: 'رقم الجوال',
    profilePhoneHelp: 'يُستخدم لإشعارات الحجز ووسائل التواصل الخاصة بالحساب.',
    profilePhoneInvalid: 'أدخل رقم جوال كويتي صحيح مكوّن من 8 أرقام.',
    themeSettings: 'المظهر',
    themeLight: 'الوضع الفاتح',
    themeDark: 'الوضع الداكن',
    languageSettings: 'اللغة',
    languageEnglish: 'الإنجليزية',
    languageArabic: 'العربية',
  },
};

export const getDashboardSharedCopy = (lang = 'en') =>
  lang === 'ar'
    ? { ...dashboardSharedCopy.en, ...repairArabicObject(dashboardSharedCopy.ar) }
    : { ...dashboardSharedCopy.en };
